modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId = "coolideas"
version = "1.0.6" #mandatory
displayName = "Cool Ideas Mod" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://github.com/MyNameTsThad/CoolIdeasMod" #optional
logoFile = "coolideas.png" #optional
credits = "ThadDev (IWant2TryHard)" #optional
authors = "ThadDev (IWant2TryHard)" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description = '''
This is just some cool ideas i have that i put into this mod.
'''