modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId = "iw2thshortbows"
version = "1.0.0" #mandatory
displayName = "IWant2TryHard's Shortbows" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://github.com/MyNameTsThad/IW2THs-Shortbows" #optional
logoFile = "iw2thshortbows.png" #optional
credits = "ThadDev (IWant2TryHard)" #optional
authors = "ThadDev (IWant2TryHard)" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description = '''
A mod that adds, well, shortbows! Shoot your foes with high speed! (And in style. Sort of.)
'''